### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by mimmi20** [etienne-martin/device-detector-js#47]
I got this error when using this library:

```shell
/home/travis/build/diablomedia/useragent-parser-comparison/parsers/device-detector-js-1/node_modules/device-detector-js/dist/parsers/client/browser.js:50
                    const match = RegExp(browserEngine.regex, "i").exec(userAgent);
                                  ^
SyntaxError: Invalid regular expression: /(?<!like )Gecko/: Invalid group
    at RegExp (<anonymous>)
    at BrowserParser.parse (/home/travis/build/diablomedia/useragent-parser-comparison/parsers/device-detector-js-1/node_modules/device-detector-js/dist/parsers/client/browser.js:50:35)
    at ClientParser.parse (/home/travis/build/diablomedia/useragent-parser-comparison/parsers/device-detector-js-1/node_modules/device-detector-js/dist/parsers/client/index.js:28:39)
    at DeviceDetector.parse (/home/travis/build/diablomedia/useragent-parser-comparison/parsers/device-detector-js-1/node_modules/device-detector-js/dist/index.js:32:43)
    at Object.<anonymous> (/home/travis/build/diablomedia/useragent-parser-comparison/parsers/device-detector-js-1/scripts/parse.js:5:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

used Node.js version: 8.9
used library version: 1.1.1

**Comment by etienne-martin** [comment]
This is fixed in [v2](https://www.npmjs.com/package/device-detector-js/v/2.0.0)
